trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePhpVersion@0
    inputs:
      versionSpec: '8.2'
      addToPath: true

  - script: |
      sudo apt-get install -y zip unzip
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
    displayName: 'Instalar Composer'

  - script: |
      composer install
    displayName: 'Instalar dependencias de PHP'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm install
      npm run prod
    displayName: 'Compilar assets de Laravel'

  - script: |
      cp .env.example .env
      php artisan key:generate
    displayName: 'Configurar entorno de Laravel'

  - script: |
      php artisan migrate --force
    displayName: 'Ejecutar migraciones de base de datos'
