trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo add-apt-repository ppa:ondrej/php -y
      sudo apt-get update
      sudo apt-get install php8.2 php8.2-cli php8.2-fpm php8.2-mbstring php8.2-xml php8.2-bcmath php8.2-curl php8.2-zip php8.2-tokenizer -y
      php -v
    displayName: 'Instalar PHP 8.2 y extensiones necesarias'

  - script: |
      sudo apt-get install -y zip unzip
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
    displayName: 'Instalar Composer'

  - script: |
      composer install
    displayName: 'Instalar dependencias de PHP'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm install
      npm run prod
    displayName: 'Compilar assets de Laravel'

  - script: |
      cp .env.example .env
      php artisan key:generate
    displayName: 'Configurar entorno de Laravel'

  - script: |
      php artisan migrate --force
    displayName: 'Ejecutar migraciones de base de datos'
